### ISSUE TITLE
buttonCornerRadii设置不生效的问题

### ISSUE THREAD

**Issue by lihuiyao1986** [boai/BAButton#1]
UIBezierPath *maskPath = [UIBezierPath bezierPathWithRoundedRect:self.bounds
                                                   byRoundingCorners:corners
                                                         ## **cornerRadii:CGSizeMake(20.0, 30.0)**];
    CAShapeLayer *maskLayer = [CAShapeLayer layer];
    maskLayer.frame         = self.bounds;
    maskLayer.path          = maskPath.CGPath;
    self.layer.mask         = maskLayer;

设置buttonCornerRadii不生效 看代码这边貌似是写死成CGSizeMake(20.0, 30.0)，可以修改一下
另外是否可以加一个padding参数 来设置图片和文字之间的间隔呢，尤其是在水平布局的话有这种需求

**Comment by boai** [comment]
这个可以，我试试！

**Comment by boai** [comment]
你可以先改下源码先用，我最近有时间改下，多谢提的需求！

**Comment by boai** [comment]
好了，我源码改完了，你试试看，如果还有问题，及时反馈下，多谢！

**Comment by boai** [comment]
pod 版本已更新，2.2.0最新！
