### ISSUE TITLE
能不能出个适配masonry

### ISSUE THREAD

**Issue by ghanyin** [boai/BAButton#10]
后来一直用masonry,几乎不设置button的frame,能不能出个友好适配masonry的

**Comment by loveuqian** [comment]
@ghanyin 
有替代品吗？

**Comment by boai** [comment]
> 后来一直用masonry,几乎不设置button的frame,能不能出个友好适配masonry的

masonry 是支持的哦！在布局完后面跟上这行代码就行！

**Comment by TML007** [comment]
> > 后来一直用masonry,几乎不设置button的frame,能不能出个友好适配masonry的
> 
> masonry 是支持的哦！在布局完后面跟上这行代码就行！

那行代码？
