### ISSUE TITLE
iphone X及以上把系统的切换键盘按钮搞没了，自定义的tabbar每次pop回来的时候都会跳动

### ISSUE THREAD

**Issue by zhoumingwu** [boai/BAButton#12]
<img width="336" alt="_4928ffd6-f9ea-4e30-80d0-929dcd16ad3b" src="https://user-images.githubusercontent.com/13554449/50438486-2163ab80-0929-11e9-91a3-d97a250ba33b.png">

**Comment by zhouxiaowei** [comment]
有毒 找bug找了一下午。。。。。发现是这个

**Comment by zhoumingwu** [comment]
我也是找了很久才发现这个问题的

发送自 Windows 10 版邮件应用

发件人: 周晓威
发送时间: 2019年1月17日 18:28
收件人: boai/BAButton
抄送: zhoumingwu; Author
主题: Re: [boai/BAButton] iphone=?UTF-8?Q?_X=E5=8F=8A=E4=BB=A5=E4=B8=8A=E6=8A=8A=E7=B3=BB=E7=BB=9F=E7=9A=84=E5=88=87=E6=8D=A2=E9=94=AE=E7=9B=98=E6=8C=89=E9=92=AE=E6=90=9E=E6=B2=A1=E4=BA=86=EF=BC=8C=E8=87=AA=E5=AE=9A=E4=B9=89=E7=9A=84tabbar=E6=AF=8F=E6=AC=A1pop=E5=9B=9E=E6=9D=A5=E7=9A=84=E6=97=B6=E5=80=99=E9=83=BD=E4=BC=9A=E8=B7=B3=E5=8A=A8?==?UTF-8?Q?_=28#12=29?=

有毒 找bug找了一下午。。。。。发现是这个

**Comment by zhouxiaowei** [comment]
> 我也是找了很久才发现这个问题的 发送自 Windows 10 版邮件应用 发件人: 周晓威 发送时间: 2019年1月17日 18:28 收件人: boai/BAButton 抄送: zhoumingwu; Author 主题: Re: [boai/BAButton] iphone=?UTF-8?Q?_X=E5=8F=8A=E4=BB=A5=E4=B8=8A=E6=8A=8A=E7=B3=BB=E7=BB=9F=E7=9A=84=E5=88=87=E6=8D=A2=E9=94=AE=E7=9B=98=E6=8C=89=E9=92=AE=E6=90=9E=E6=B2=A1=E4=BA=86=EF=BC=8C=E8=87=AA=E5=AE=9A=E4=B9=89=E7=9A=84tabbar=E6=AF=8F=E6=AC=A1pop=E5=9B=9E=E6=9D=A5=E7=9A=84=E6=97=B6=E5=80=99=E9=83=BD=E4=BC=9A=E8=B7=B3=E5=8A=A8?==?UTF-8?Q?_=28#12=29?= 有毒 找bug找了一下午。。。。。发现是这个 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

注释掉 UIButton+BAKit.m  

//- (void)setFrame:(CGRect)frame
//{
//    [super setFrame:frame];
//    [self setupBAButtonLayout];
//}

就好了

**Comment by boai** [comment]
2.6.8 版本已修复，大家更新最新版本即可！
