### ISSUE TITLE
设置圆角无效。然后btn都没了

### ISSUE THREAD

**Issue by QionglinFu1024** [boai/BAButton#13]
-(UIButton *)commitBtn
{
    if (!_commitBtn)
    {
        _commitBtn = [UIButton ba_creatButtonWithFrame:CGRectZero title:@"完成" selTitle:@"完成" titleColor:KBackgroundColor_FF titleFont:[UIFont systemFontOfSize:16] image:nil selImage:nil padding:0 buttonPositionStyle:BAKit_ButtonLayoutTypeNormal viewRectCornerType:BAKit_ViewRectCornerTypeAllCorners viewCornerRadius:8 target:self selector:@selector(commitBtnClick)];
    }
    return _commitBtn;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    [self.view addSubview:self.commitBtn];
    [self.commitBtn mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.offset(20);
        make.right.offset(-20);
        make.bottom.offset(-3);
        make.height.offset(44);
    }];

}
只要不用设置圆角的都能正常显示。一设置就没戏。救救孩子～

**Comment by boai** [comment]
这里的设置圆角 一定要在 layout 之后 设置圆角，一般 在 layoutsubviews 里面写
