### ISSUE TITLE
这个图片上文字下以及文字上图片下都有点问题

### ISSUE THREAD

**Issue by BetterAnn** [boai/BAButton#2]
图片上文字下：一旦图片的高度的80%大于按钮高度的50%，就会出现图片显示不全的问题以及文字会有一部分压在图片上
文字上图片下：一旦图片的高度的80%大于按钮高度的50%，就会出现图片显示不全的问题

**Comment by boai** [comment]
你加我 QQ：137361770，发demo给我，我看看

**Comment by liyanyan77** [comment]
button 的frame都是事先写死的 如果能做到根据 button的图片与文字实现frame的自适应 就更完美了

**Comment by boai** [comment]
frame 是在外面设定的，所以要根据自己的图片大小和文字大小来设置frame！

**Comment by BetterAnn** [comment]
嗷嗷，回来我再试试

**Comment by gdzpf123** [comment]
有办法控制内容居中，图左文右的样式时，能够设置图片的大小么？

**Comment by boai** [comment]
可以，需要自己设置图片大小，具体看新 demo，有自定义大小适配！
