### ISSUE TITLE
||  条件一定是成立的 会一直取三目运算符第一个

### ISSUE THREAD

**Issue by longxingtianxiaShuai** [boai/BAButton#6]
#define BAKit_SCREEN_WIDTH ((([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationPortrait) || ([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationPortraitUpsideDown)) ? [[UIScreen mainScreen] bounds].size.width : [[UIScreen mainScreen] bounds].size.height)

**Comment by boai** [comment]
你再好好理解下！
