### ISSUE TITLE
如何调整BAButton内部的ImgView的大小

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [boai/BAButton#8]
您好，我发现不能调整BAButton内部ImgView的大小，它的大小只能根据button的大小自动生成，这样不太友好吧

**Comment by boai** [comment]
这个是 button 的分类，只是扩展了部分功能，改变image 的大小，可以实现，demo 中也有，去好好看demo！

**Comment by liunianhuaguoyanxi** [comment]
您好，我的意思是没法给ImgView设置固定的值，只能根据button的大小自动生成，改变image 的大小也只有等比缩放，dome中的ba_imageScaleToWidth
